### ISSUE TITLE
Error in elastool

### ISSUE THREAD

**Issue by shahramyalameha** [zhongliliu/elastool#10]
Dear developers, 
I get the following execution error while installing the latest version of elastool (v3.64). How can I fix it?

```
Traceback (most recent call last):
  File "/home/shahram/.local/bin/elastool", line 8, in <module>
    from find_spg import find_crystal_system
  File "/home/shahram/.local/lib/python3.10/site-packages/find_spg.py", line 18, in <module>
    from read_input import indict
  File "/home/shahram/.local/lib/python3.10/site-packages/read_input.py", line 195, in <module>
    indict = read_input()
  File "/home/shahram/.local/lib/python3.10/site-packages/read_input.py", line 81, in read_input
    if inputlist[1] == []:
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/shahram/.local/bin/elastool", line 10, in <module>
    from find_spg import find_crystal_system
  File "/home/shahram/.local/lib/python3.10/site-packages/find_spg.py", line 18, in <module>
    from read_input import indict
  File "/home/shahram/.local/lib/python3.10/site-packages/read_input.py", line 28, in <module>
    from elastoolgui import elastoolguicall
ModuleNotFoundError: No module named 'elastoolgui'
```
elastool.in is:

```
###############################################################################
### The input file to control the calculation details of elastic constants  ###
###############################################################################

# run mode: 1 for automatic run, 2 for pre-processing, 3 for post-processing
# if 2, plz ensure the structure opt. is performed at fixed pressure or volume
# i.e. CONTCAR and OUTCAR files both exist in ./OPT directory.
run_mode = 2

# Define the dimensional of the system: 2D/3D
dimensional = 1D

# the crystal structure file in vasp POSCAR (.vasp) or cif (.cif) format
structure_file = OPT.cif

# if use conventional cell, no for primitive cell, yes for conventional cell
if_conventional_cell = no

# static or dynamic, static for 0 K, dynamic for finite-temperature
method_stress_statistics = static

# strains matrix for solve all elastic constants, asess or ohess or ulics
strains_matrix = ohess

# strains list for deforming lattice cell, 0 will be neglected because of 
# the initial optimization, if method_statistics = dynamic, the first one is used
strains_list = -0.06 -0.03 0.03 0.06

# repeat numbers of three lattice vectors in conventional lattice for making
# supercell of molecular dynamics simulations (method_statistics = dynamic)
repeat_num = 3 3 3

# last number of steps for sampling stresses used in the dynamic method
num_last_samples = 1000

#Potential directory - specify the location of your POTCAR files
potential_dir = /home/shahram/Sotf/vasp.6.3.0/PAW_PBE

# The parallel submiting commmd
parallel_submit_command = ff > log.vasp
```

Thanks, 
Shahram

**Comment by gmp007** [comment]
It was a mistake on my part. I forgot to include the elastoolgui in the recent version. Can you unistall and install it again with pip install -U elastool

**Comment by shahramyalameha** [comment]
Thank you for your reply. Error `elastoolgui` is fixed but the following error still exists:
```
Traceback (most recent call last):
  File "/home/shahram/.local/bin/elastool", line 10, in <module>
    from find_spg import find_crystal_system
  File "/home/shahram/.local/lib/python3.10/site-packages/find_spg.py", line 18, in <module>
    from read_input import indict
  File "/home/shahram/.local/lib/python3.10/site-packages/read_input.py", line 208, in <module>
    indict = read_input()
  File "/home/shahram/.local/lib/python3.10/site-packages/read_input.py", line 84, in read_input
    if inputlist[1] == []:
```
I have to do the calculations for a nanoribbon with elastool, which file POSCAR is as follows:

```
Al Sb                                   
   1.00000000000000     
     7.3452057932200319    0.0000000000000000   -0.0005089136455573
     0.0000000000000000   35.0384299224228926    0.0000000000000000
    -0.0024255464761344    0.0000000000000000   34.9872865538147479
   Al   Sb
     4     4
Direct
  0.1480973706836346  0.4777149682094700  0.5259224913609446
  0.6480973866836289  0.5222850317905442  0.5259224913609446
  0.3519026943163601  0.5222850317905442  0.4740774546390581
  0.8519026293163724  0.4777149682094700  0.4740774546390581
  0.1874822698717630  0.4579711333229955  0.4516063041040464
  0.6874822858717573  0.5420288666770116  0.4516063041040464
  0.3125177951282317  0.5420288666770116  0.5483936958959608
  0.8125177301282440  0.4579711333229955  0.5483936958959608
```

Is there a problem with the POSCAR file?

Thanks, 
Shahram

**Comment by gmp007** [comment]
It's hard to tell by looking at your structure. I suggest you run some examples to understand the input structure, which must be eith *.cif or *.vasp format and extension, respectively. 

Since the error of last time has been resolved, I will go ahead and close this thread. You're more than welcome to reopen it if you need or have any other questions.
